"""add analysis runs

Revision ID: 24234f16272d
Revises: 6fa2f66bc07f
Create Date: 2026-03-15 22:43:39.149198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24234f16272d'
down_revision = '6fa2f66bc07f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('documents_processed', sa.Integer(), nullable=False),
    sa.Column('topics_created', sa.Integer(), nullable=False),
    sa.Column('trend_rows_created', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_id'), 'analysis_runs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_runs_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
