"""initial schema

Revision ID: 6fa2f66bc07f
Revises: 
Create Date: 2026-03-12 22:59:13.501654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa2f66bc07f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('text_raw', sa.Text(), nullable=False),
    sa.Column('text_clean', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_documents_url')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_published_at'), 'documents', ['published_at'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_table('trend_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mentions_count', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('sentiment_avg', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'date', name='uq_trend_metrics_topic_date')
    )
    op.create_index(op.f('ix_trend_metrics_date'), 'trend_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_trend_metrics_id'), 'trend_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_trend_metrics_topic_id'), 'trend_metrics', ['topic_id'], unique=False)
    op.create_table('document_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_document_topics_document_id')
    )
    op.create_index(op.f('ix_document_topics_document_id'), 'document_topics', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_topics_id'), 'document_topics', ['id'], unique=False)
    op.create_index(op.f('ix_document_topics_topic_id'), 'document_topics', ['topic_id'], unique=False)
    op.create_table('sentiment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_sentiment_results_id'), 'sentiment_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_results_id'), table_name='sentiment_results')
    op.drop_table('sentiment_results')
    op.drop_index(op.f('ix_document_topics_topic_id'), table_name='document_topics')
    op.drop_index(op.f('ix_document_topics_id'), table_name='document_topics')
    op.drop_index(op.f('ix_document_topics_document_id'), table_name='document_topics')
    op.drop_table('document_topics')
    op.drop_index(op.f('ix_trend_metrics_topic_id'), table_name='trend_metrics')
    op.drop_index(op.f('ix_trend_metrics_id'), table_name='trend_metrics')
    op.drop_index(op.f('ix_trend_metrics_date'), table_name='trend_metrics')
    op.drop_table('trend_metrics')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_published_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
